### ISSUE TITLE
Use production environment in all containers

### ISSUE THREAD

**Issue by michielbdejong** [michielbdejong/fxa-self-hosting#10]
Some containers use the 'dev' or 'local' environment, which (even if it works) is not security best-practice.
- [x] docker build -f ./docs/self-host.docker -t fxa-content-server https://github.com/michielbdejong/fxa-content-server.git#docker
- [x] docker build -f ./docs/self-host.docker -t fxa-auth-server https://github.com/michielbdejong/fxa-auth-server.git#docker
- [x] docker build -f ./docs/self-host.docker -t fxa-auth-db-mysql https://github.com/michielbdejong/fxa-auth-db-mysql.git#docker
- [x] docker build -f ./docs/self-host.docker -t fxa-oauth-server https://github.com/michielbdejong/fxa-oauth-server.git#docker
- [x] docker build -f ./docs/self-host.docker -t browserid-verifier https://github.com/michielbdejong/browserid-verifier.git#docker
- [ ] docker build -f ./docs/self-host.docker -t fxa-profile-server https://github.com/michielbdejong/fxa-profile-server.git#docker
- [ ] docker build -t syncserver https://github.com/michielbdejong/syncserver.git#docker
- [ ] docker build -t syncto https://github.com/michielbdejong/syncto.git#docker

**Comment by michielbdejong** [comment]
- fxa-auth-server: Having some trouble building with prod env:

```
Generating keypair
Secret Key saved: /home/fxa/fxa-auth-server/config/secret-key.json

undefined:0

^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /home/fxa/fxa-auth-server/scripts/gen_keys.js:49:18
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```
- fxa-profile-server: There does not seem to be a prod equivalent of https://github.com/mozilla/fxa-profile-server/blob/master/scripts/run_dev.js

**Comment by michielbdejong** [comment]
browserid-verifier does not seem to distinguish between run environments, afaics.

**Comment by michielbdejong** [comment]
~~Testing unpushed changes for:~~
~~\* fxa-content-server~~
~~\* fxa-oauth-server~~
~~\* fxa-auth-server~~

**Comment by michielbdejong** [comment]
To do:
- fxa-profile-server: https://github.com/mozilla/fxa-profile-server/blob/master/scripts/run_dev.js#L13
- syncserver: https://github.com/mozilla-services/syncserver/blob/master/Makefile#L24
- syncto: https://github.com/mozilla-services/syncto/blob/master/Makefile#L1
