### ISSUE TITLE
Problem building fxa-auth-server on debian9

### ISSUE THREAD

**Issue by laubosslink** [michielbdejong/fxa-self-hosting#18]
Hey I tried to run ./build.sh then ./setup.sh mydomain, the setup didn't have 9 container setup, so I checked each build line by line, and the following have a problem : 

```
root@firefox:~/fxa-self-hosting# docker build -f ./docs/self-host.docker -t fxa-auth-server https://github.com/mozilla/fxa-auth-server.git
```

```
...
npm WARN engine shelljs@0.7.8: wanted: {"node":">=0.11.0","iojs":"*"} (current: {"node":"0.10.38","npm":"2.8.4"})
npm WARN engine esprima@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.38","npm":"2.8.4"})

> fxa-geodb@0.0.8 postinstall /home/fxa/fxa-auth-server/node_modules/fxa-geodb
> LOG=quiet node scripts/start-db-download.js

{"Timestamp":1502511457097000000,"Logger":"fxa-geodb","Type":"uncaughtException","Severity":0,"Pid":161,"EnvVersion":"2.0","Fields":{"error":"TypeError: Object #<Object> has no method 'parse'","stack":"\n    at setupDownloadList (/home/fxa/fxa-auth-server/node_modules/fxa-geodb/lib/maxmind-db-downloader.js:58:33)\n    at Object.<anonymous> (/home/fxa/fxa-auth-server/node_modules/fxa-geodb/scripts/start-db-download.js:18:54)\n    at Module._compile (module.js:456:26)\n    at Object.Module._extensions..js (module.js:474:10)\n    at Module.load (module.js:356:32)\n    at Function.Module._load (module.js:312:12)\n    at Function.Module.runMain (module.js:497:10)\n    at startup (node.js:119:16)\n    at node.js:935:3"}}
npm WARN optional dep failed, continuing fsevents@1.1.2
npm WARN engine string-width@2.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.38","npm":"2.8.4"})
npm WARN engine strip-ansi@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.38","npm":"2.8.4"})
npm WARN engine is-fullwidth-code-point@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.38","npm":"2.8.4"})
npm WARN engine ansi-regex@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.38","npm":"2.8.4"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.38","npm":"2.8.4"})
npm ERR! Linux 4.9.0-3-amd64
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v0.10.38
npm ERR! npm  v2.8.4
npm ERR! code ELIFECYCLE

npm ERR! fxa-geodb@0.0.8 postinstall: `LOG=quiet node scripts/start-db-download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fxa-geodb@0.0.8 postinstall script 'LOG=quiet node scripts/start-db-download.js'.
npm ERR! This is most likely a problem with the fxa-geodb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     LOG=quiet node scripts/start-db-download.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fxa-geodb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fxa/fxa-auth-server/npm-debug.log
```

**Comment by vladikoff** [comment]
> npm ERR! node v0.10.38


@laubosslink You need `node v4`
