### ISSUE TITLE
no nodes in poolee for fxa-auth-server

### ISSUE THREAD

**Issue by michielbdejong** [michielbdejong/fxa-self-hosting#7]
{"Timestamp":1452874928853000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":2,"Pid":5,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":503,"errno":999,"rid":"1452874928836:e323ce97fd18:5:ijfw4blq:10022","path":"/v1/account/profile","remoteAddressChain":"[\"172.17.1.169\"]","t":17,"uid":"00","stack":"Error: no nodes\n    at Object.exports.create (/home/fxa/fxa-auth-server/node_modules/hapi-fxa-oauth/node_modules/boom/lib/index.js:21:17)\n    at Object.exports.internal (/home/fxa/fxa-auth-server/node_modules/hapi-fxa-oauth/node_modules/boom/lib/index.js:252:92)\n    at Object.exports.serverTimeout (/home/fxa/fxa-auth-server/node_modules/hapi-fxa-oauth/node_modules/boom/lib/index.js:276:20)\n    at /home/fxa/fxa-auth-server/node_modules/hapi-fxa-oauth/index.js:86:31\n    at RequestSet.callback (/home/fxa/fxa-auth-server/node_modules/hapi-fxa-oauth/node_modules/poolee/lib/pool.js:131:4)\n    at RequestSet.handleResponse (/home/fxa/fxa-auth-server/node_modules/hapi-fxa-oauth/node_modules/poolee/lib/request_set.js:66:8)\n    at Endpoint.unhealthy.request (/home/fxa/fxa-auth-server/node_modules/hapi-fxa-oauth/node_modules/poolee/lib/endpoint.js:359:12)\n    at RequestSet.doRequest (/home/fxa/fxa-auth-server/node_modules/hapi-fxa-oauth/node_modules/poolee/lib/request_set.js:89:7)\n    at Timer.listOnTimeout [as ontimeout](timers.js:112:15)"}}

**Comment by michielbdejong** [comment]
Seeing `Endpoint({ Agent: [Function: Object] }, null, null, { timeout: 0 })` in /home/fxa/fxa-auth-server/node_modules/hapi-fxa-oauth/node_modules/poolee/index.js

**Comment by michielbdejong** [comment]
Fixed in fe4d6a1
